### ISSUE TITLE
layoutSubviews 内部代码 需要修改一下

### ISSUE THREAD

**Issue by wait10000y** [watermelon520/LPAutoScrollView#2]
LPAutoScrollView.m

// 需要修改一下, 你原来的标记,只会自动更新界面布局一次
// lastFrame 界面的上一状态的 frame
- (void)layoutSubviews {
  [super layoutSubviews];
  if (CGRectEqualToRect(self.frame, lastFrame)) {
    return;
  }

//TODO: update code

lastFrame = self.frame;
}

**Comment by watermelon520** [comment]
确实是一个问题，谢谢你的建议
